Models/Players.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace HomeTeamWebSite.Models
{
    public class Players
    {
        public int idPlayer { get; set; }
        public string strNationality { get; set; }
        public string strPlayer { get; set; }
        public string strNumber { get; set; }
        public string strPosition { get; set; }
        public string strHeight { get; set; }
        public string strtSide { get; set; }
        public string strTeam { get; set; }
        public string strTeam2 { get; set; }
        public string strKit { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime dateBorn { get; set; }
        public string strBirthLocation { get; set; }
        public string strWage { get; set; }
        public string strSigning { get; set; }
        public string strAgent { get; set; }
        public string strCutout { get; set; }
        public string strtThumb { get; set; }
    }
}

Controllers/PlayersController.cs
using HomeTeamWebSite.Models;
using Newtonsoft.Json;
using System;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace HomeTeamWebSite.Controllers
{
    public class PlayersController : Controller
    {
        public async Task<ActionResult> Index(string searchString = "")
        {
            using (HttpClient client = new HttpClient())
            {

                string apiUrl = "https://www.thesportsdb.com/api/v1/json/3/searchplayers.php?t=Arsenal";
                HttpResponseMessage response = await client.GetAsync(apiUrl);

                if (response.IsSuccessStatusCode)
                {
                    string json = await response.Content.ReadAsStringAsync();
                    var responseObj = JsonConvert.DeserializeObject<PlayerResponse>(json);

                    // Filtra i giocatori se searchString non è vuoto
                    if (!String.IsNullOrEmpty(searchString))
                    {
                        // Applica ToLower() per un confronto case-insensitive
                        var searchStringLower = searchString.ToLower();
                        responseObj.player = responseObj.player.Where(p => p.strPlayer != null && p.strPlayer.ToLower().Contains(searchStringLower)).ToList();
                    }

                    return View(responseObj.player);
                }
                else
                {
                    return View("Error");
                }
            }
        }

    }

}

Views/Players/Index.cshtml
@model IEnumerable<HomeTeamWebSite.Models.Players>



<style>
    body {
        background: url('../Content/img/sfondoHome.jpg') no-repeat;
        background-size: cover;
        background-position-x: center;
        background-attachment: fixed;
    }

    input {
        max-width: 300px;
    }
</style>

<h1 class="text-center my-3 titolo-player">Our Player - Your Gunners</h1>


<div class="container">
    @using (Html.BeginForm("Index", "Players", FormMethod.Get))
    {
        <div class="my-4 ">
            <div class="input-group">
                <input type="text" class="form-control" name="searchString" placeholder="Search Player..." aria-label="Nome Giocatore">
                <button type="submit" class="btn btn-dark fw-bold">Search</button>
            </div>
        </div>

    }


    <div class="row min-vh-100">

        @foreach (var player in Model)
        {
            <div class="col-sm-12 col-md-6">
                <div class="card mb-2 bg-white bg-opacity-75">
                    <div class="row">
                        <div class="col-md-12 col-lg-6 col-xlg-4">
                            <img src="@player.strCutout" alt="img player" class="img-fluid">
                        </div>
                        <div class="col-md-12 col-lg-6 col-xlg-8">
                            <div class="card-body">
                                <h3 class="card-title">@player.strPlayer</h3>

                                <div class="d-flex">
                                    <p class="card-text fw-bold">@String.Format("{0:dd/MM/yyyy}", player.dateBorn)</p>
                                    <p class="card-text ms-2 fw-bold">@player.strNationality</p>
                                </div>
                                <p class="card-tex fw-bold">Position: @player.strPosition</p>

                                <button type="button" class="custom-btn-player" data-bs-toggle="modal" data-bs-target="#playerModal_@player.idPlayer">
                                    Show Details
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="modal fade" id="playerModal_@player.idPlayer" tabindex="-1" aria-labelledby="playerModalLabel_@player.idPlayer" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title " id="playerModalLabel_@player.idPlayer">Player's Details</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <p><strong>Name:</strong> @player.strPlayer</p>
                            <p><strong>Date Born:</strong> @String.Format("{0:dd/MM/yyyy}", player.dateBorn)</p>
                            <p><strong>Birth Location:</strong> @player.strBirthLocation</p>
                            <p><strong>Nationality:</strong> @player.strNationality</p>
                            <p><strong>Position:</strong> @player.strPosition</p>
                            
                            @if (player.strNumber != null)
                            {
                                <p><strong>Number:</strong> @player.strNumber</p>
                            }
                            else
                            {
                                <p><strong>WHAT THE ROCK IS COOKING</strong></p>
                            }

                            <p><strong>Height:</strong> @player.strHeight</p>
                            <p><strong>Wage:</strong> @player.strWage</p>
                            <p><strong>Value</strong> @player.strSigning</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>