Controllers/PartiteController.cs
using HomeTeamWebSite.Models;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace HomeTeamWebSite.Controllers
{
    public class PartiteController : Controller
    {
        private ArsenalDbContext db = new ArsenalDbContext();

        // GET: Partite
        public ActionResult Index()
        {
            return View(db.Partite.ToList());
        }

        // GET: Partite/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Partite partite = db.Partite.Find(id);
            if (partite == null)
            {
                return HttpNotFound();
            }
            return View(partite);
        }

        // GET: Partite/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Partite/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdPartita,Data,SquadraCasa,SquadraOspite")] Partite partite)
        {
            if (ModelState.IsValid)
            {
                db.Partite.Add(partite);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(partite);
        }

        // GET: Partite/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Partite partite = db.Partite.Find(id);
            if (partite == null)
            {
                return HttpNotFound();
            }
            return View(partite);
        }

        // POST: Partite/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdPartita,Data,SquadraCasa,SquadraOspite")] Partite partite)
        {
            if (ModelState.IsValid)
            {
                db.Entry(partite).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(partite);
        }

        // GET: Partite/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Partite partite = db.Partite.Find(id);
            if (partite == null)
            {
                return HttpNotFound();
            }
            return View(partite);
        }

        // POST: Partite/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Partite partite = db.Partite.Find(id);
            db.Partite.Remove(partite);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult CheckSeats(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ViewBag.IdPartita = id;
            return RedirectToAction("Index", "TipoPosto", new { idPartita = id });
        }

    }
}

Controllers/ProdottiController.cs
using HomeTeamWebSite.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace HomeTeamWebSite.Controllers
{
    public class ProdottiController : Controller
    {
        private ArsenalDbContext db = new ArsenalDbContext();

        // GET: Prodotti
        public ActionResult Index()
        {
            return View(db.Prodotti.ToList());
        }

        // GET: Prodotti/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prodotti prodotti = db.Prodotti.Find(id);
            if (prodotti == null)
            {
                return HttpNotFound();
            }
            return View(prodotti);
        }

        [Authorize(Roles = "Admin")]
        // GET: Prodotti/Create
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdProdotto,NomeProdotto,Descrizione,Prezzo,Immagine, Immagine2, Immagine3")] Prodotti prodotti, IEnumerable<HttpPostedFileBase> files)
        {
            try
            {
                List<string> uploadedFiles = new List<string>();
                foreach (var file in files)
                {
                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        var path = Path.Combine(Server.MapPath("~/Content/imgProdotti"), fileName);
                        System.Diagnostics.Debug.WriteLine("Percorso di salvataggio: " + path);
                        if (!Directory.Exists(Server.MapPath("~/Content/imgProdotti/")))
                        {
                            Directory.CreateDirectory(Server.MapPath("~/Content/imgProdotti"));
                        }
                        file.SaveAs(path);
                        uploadedFiles.Add(fileName);  // Add file name to the list
                    }
                }

                if (uploadedFiles.Count > 0)
                {
                    prodotti.Immagine = uploadedFiles.Count > 0 ? uploadedFiles.ElementAtOrDefault(0) : "/Content/imgProdotti/default.jpg";
                    prodotti.Immagine2 = uploadedFiles.Count > 1 ? uploadedFiles.ElementAtOrDefault(1) : "/Content/imgProdotti/default.jpg";
                    prodotti.Immagine3 = uploadedFiles.Count > 2 ? uploadedFiles.ElementAtOrDefault(2) : "/Content/imgProdotti/default.jpg";
                }
                else
                {
                    prodotti.Immagine = "/Content/imgProdotti/default.jpg";
                    prodotti.Immagine2 = "/Content/imgProdotti/default.jpg";
                    prodotti.Immagine3 = "/Content/imgProdotti/default.jpg";
                }

                if (ModelState.IsValid)
                {
                    db.Prodotti.Add(prodotti);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine("Errore durante il salvataggio del file: " + ex.Message);
            }

            return View(prodotti);
        }


        // GET: Prodotti/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prodotti prodotti = db.Prodotti.Find(id);
            if (prodotti == null)
            {
                return HttpNotFound();
            }
            return View(prodotti);
        }

        // POST: Prodotti/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdProdotto,NomeProdotto,Descrizione,Prezzo,Immagine")] Prodotti prodotti)
        {
            if (ModelState.IsValid)
            {
                db.Entry(prodotti).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(prodotti);
        }

        // GET: Prodotti/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prodotti prodotti = db.Prodotti.Find(id);
            if (prodotti == null)
            {
                return HttpNotFound();
            }
            return View(prodotti);
        }

        // POST: Prodotti/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Prodotti prodotti = db.Prodotti.Find(id);
            db.Prodotti.Remove(prodotti);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        // Action per aggiungere un prodotto al carrello
        public ActionResult AddToCart(int id, int Quantita)
        {

            if (!User.Identity.IsAuthenticated)
            {
                TempData["AddCartFailed"] = "You must be logged in to add a product to the cart";
                return RedirectToAction("Index", "Home");

            }

            var prodotto = db.Prodotti.Find(id);

            if (prodotto != null)
            {
                var cart = Session["cart"] as List<Prodotti> ?? new List<Prodotti>();
                prodotto.Quantita = Quantita;
                if (cart.Any(p => p.IdProdotto == id))
                {
                    var prodottoInCart = cart.First(p => p.IdProdotto == id);
                    prodottoInCart.Quantita += Quantita;
                }
                else
                {
                    cart.Add(prodotto);
                    Session["cart"] = cart;
                    TempData["AddCart"] = "Product added to the cart";
                }
            }
            return RedirectToAction("Index");
        }

    }
}

Controllers/UtentiController.cs
using HomeTeamWebSite.Models;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace HomeTeamWebSite.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UtentiController : Controller
    {
        private ArsenalDbContext db = new ArsenalDbContext();

        // GET: Utenti
        public ActionResult Index()
        {
            return View(db.Utenti.ToList());
        }

        // GET: Utenti/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utenti utenti = db.Utenti.Find(id);
            if (utenti == null)
            {
                return HttpNotFound();
            }
            return View(utenti);
        }

        // GET: Utenti/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Utenti/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdUtente,Nome,Cognome,Mail,Psw,Ruolo,Username,TipoAccount")] Utenti utenti)
        {
            if (ModelState.IsValid)
            {
                db.Utenti.Add(utenti);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(utenti);
        }

        // GET: Utenti/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utenti utenti = db.Utenti.Find(id);
            if (utenti == null)
            {
                return HttpNotFound();
            }
            return View(utenti);
        }

        // POST: Utenti/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdUtente,Nome,Cognome,Mail,Psw,Ruolo,Username,TipoAccount")] Utenti utenti)
        {
            if (ModelState.IsValid)
            {
                db.Entry(utenti).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(utenti);
        }

        // GET: Utenti/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utenti utenti = db.Utenti.Find(id);
            if (utenti == null)
            {
                return HttpNotFound();
            }
            return View(utenti);
        }

        // POST: Utenti/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Utenti utenti = db.Utenti.Find(id);
            db.Utenti.Remove(utenti);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult UpGrade(int id)
        {
            Utenti utenti = db.Utenti.Find(id);
            utenti.TipoAccount = "Premium";
            db.Entry(utenti).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DownGrade(int id)
        {
            Utenti utenti = db.Utenti.Find(id);
            utenti.TipoAccount = "Standard";
            db.Entry(utenti).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Applicazione ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css" rel="stylesheet">


</head>
<body>
    <nav class="navbar navbar-expand-md navbar-toggleable-md navbar-dark bg-dark">
        <div class="container-fluid">
            <img src="~/Content/img/ArsenalLogo.png" class="logo-nav mb-2" width="100" />
            @Html.ActionLink("Nome applic", "Index", "Home", new { area = "" }, new { @class = "navbar-brand text-dark" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Attiva/Disattiva spostamento" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-md-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Home", "Home", new { area = "" }, new { @class = "nav-link text-center text-white " })</li>
                    <li>@Html.ActionLink("Official Store", "Index", "Prodotti", new { area = "" }, new { @class = "nav-link text-center text-white" })</li>
                    <li>@Html.ActionLink("Matches - Tickets", "Index", "Partite", new { area = "" }, new { @class = "nav-link text-center text-white" })</li>
                    <li>@Html.ActionLink("Players", "Index", "Players", new { area = "" }, new { @class = "nav-link text-center text-white" })</li>
                    <li>@Html.ActionLink("Standings", "Index", "Standing", new { area = "" }, new { @class = "nav-link text-center text-white" })</li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("User Managment", "Index", "Utenti", new { area = "" }, new { @class = "nav-link text-center text-white" })</li>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Logout", "Logout", "Home", new { area = "" }, new { @class = "nav-link text-center text-danger " })</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("| SignIn - SignUp", "Index", "Home", new { area = "" }, new { @class = "nav-link text-center text-white" })</li>
                    }
                </ul>
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-link text-center text-white logo-user"><i class="bi bi-person-circle"></i> @User.Identity.Name</li>
                    </ul>
                }

            </div>
        </div>
    </nav>

    <div class="">
        @RenderBody()
        <hr class="my-0 py-0" />
        <footer class="bg-dark my-0 py-0" id="footer">
            <div class="container">
                <h5 class="text-center text-white py-2">Follow us on all social media platforms</h5>
                <div class="d-flex p-2 justify-content-around">

                    <a href="https://www.instagram.com/arsenal/" target="_blank"> <img src="~/Content/img/instagram.png" alt="instagram  logo" width="50" height="40" /></a>
                    @{
                        string tiktokLink = "https://www.tiktok.com/@arsenal";
                    }
                    <a href="@tiktokLink" target="_blank"><img src="~/Content/img/tiktok.png" alt="twitter logo" width="50" height="40" /></a>
                    <a href="https://t.me/s/arsenalivetv?before=5019" target="_blank"><img src="~/Content/img/telegram.png" alt="telegram logo" width="50" height="40" /></a>
                    <a href="https://twitter.com/Arsenal" target="_blank"><img src="~/Content/img/twitter.png" width="50" height="40" /></a>
                    <a href="https://www.facebook.com/Arsenal" target="_blank"><img src="~/Content/img/facebook.png" width="50" height="40" /></a>
                </div>
            </div>
            <div class="mx-5">
                <p class="text-white text-center m-0 py-2">
                    &copy; @DateTime.Now.Year - Made By Nat.
                    <br />All rights reserved. No part of this publication may be reproduced, distributed, or transmitted in any form or by any means, including photocopying, recording, or other electronic or mechanical methods, without the prior written permission of the publisher, except in the case of brief quotations embodied in critical reviews and certain other noncommercial uses permitted by copyright law.
                </p>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

</body>
</html>