Controllers/CarrelloController.cs
using HomeTeamWebSite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace HomeTeamWebSite.Controllers
{
    public class CarrelloController : Controller
    {
        // GET: Carrello
        public ActionResult Index()
        {
            var cart = Session["cart"] as List<Prodotti>;
            if (cart == null || !cart.Any())
            {
                return RedirectToAction("Index", "Prodotti");
            }
            return View(cart);
        }


        // Action per la gestione quantita e push su DB DettagliVnedita
        [HttpPost]
        public ActionResult Order()
        {
            ArsenalDbContext db = new ArsenalDbContext();

            var userId = db.Utenti.FirstOrDefault(u => u.Username == User.Identity.Name).IdUtente;


            var cart = Session["cart"] as List<Prodotti>;

            if (cart != null && cart.Any())
            {
                Ordini ordini = new Ordini();

                ordini.IdUtente = userId;
                ordini.DataOrdine = DateTime.Now;
                db.Ordini.Add(ordini);
                db.SaveChanges();

                foreach (var product in cart)
                {
                    DettaglioVendita dettaglioVendita = new DettaglioVendita();

                    dettaglioVendita.IdProdotto = product.IdProdotto;
                    dettaglioVendita.IdOrdine = ordini.IdOrdine;
                    dettaglioVendita.QuantitaProdotti = Convert.ToInt32(product.Quantita);
                    dettaglioVendita.PrezzoUnitario = product.Prezzo;

                    db.DettaglioVendita.Add(dettaglioVendita);
                    db.SaveChanges();

                }
                cart.Clear();
            }
            TempData["Order"] = "Order placed successfully!";

            return RedirectToAction("Index", "Prodotti");

        }

        // Action per la rimozione di un prodotto dal carrello

        public ActionResult Delete(int? id)
        {
            var cart = Session["cart"] as List<Prodotti>;
            if (cart != null)
            {
                var productRemove = cart.FirstOrDefault(p => p.IdProdotto == id);
                if (productRemove != null)
                {
                    if (productRemove.Quantita > 1)
                    {
                        productRemove.Quantita--;
                    }
                    else
                    {
                        cart.Remove(productRemove);
                    }
                }
            }
            return RedirectToAction("Index");
        }



        public ActionResult CartClear()
        {
            var cart = Session["cart"] as List<Prodotti>;
            if (cart != null)
            {
                cart.Clear();
            }
            TempData["CreateMess"] = "The cart has been emptied";
            return RedirectToAction("Index", "Prodotti");
        }
    }
}

Views/Carrello/Index.cshtml
@model IEnumerable<HomeTeamWebSite.Models.Prodotti>


@{
    ViewBag.Title = "Index";
}

<style>
    body {
        background-color: #F1F2F3;
    }
</style>




<h1 class="text-center bebas-neue-regular">SUMMARY</h1>

<div class="container">
    <div class="row">
        <div class="col-lg-6">
            @foreach (var item in Model)
            {
                <div class="card mb-3" style="width: auto;">
                    <div class="row g-0">
                        <div class="col-md-12">
                            <img src="~/Content/imgProdotti/@item.Immagine" class="card-img-top" alt="...">
                        </div>
                    </div>
                    <div class="row g-0">
                        <div class="col-md-12">
                            <div class="card-body">
                                <h5 class="card-title">@Html.DisplayFor(modelItem => item.NomeProdotto)</h5>
                                <p class="card-text">@Html.DisplayFor(modelItem => item.Descrizione)</p>
                                <p class="card-text"><span class="text-muted">Quantity: @Html.DisplayFor(modelItem => item.Quantita)</span></p>
                                <p class="card-text fw-bold">Price: @String.Format("{0:F2}", (item.Prezzo * item.Quantita)) £</p>
                                <a href="@Url.Action("Delete", new { id = item.IdProdotto })" class="btn btn-danger">Remove From Cart</a>
                            </div>
                        </div>
                    </div>
                </div>

            }

        </div>
        <div class="col-lg-6">
            <div class="card mb-3">
                <div class="card-header fw-bold ">
                    Checkout
                </div>
                <div class="card-body">
                    <form>
                        <div class="form-group">
                            <label for="nome">Name:</label>
                            <input type="text" class="form-control" id="nome" name="nome" required>
                        </div>
                        <div class="form-group">
                            <label for="cognome">Surname:</label>
                            <input type="text" class="form-control" id="cognome" name="cognome" required>
                        </div>
                        <div class="form-group">
                            <label for="indirizzo">Street Address:</label>
                            <input type="text" class="form-control" id="indirizzo" name="indirizzo" required>
                        </div>
                        <div class="form-group">
                            <label for="citta">City/Town:</label>
                            <input type="text" class="form-control" id="citta" name="citta" required>
                        </div>
                        <div class="form-group">
                            <label for="cap">Postal Code:</label>
                            <input type="text" class="form-control" id="cap" name="cap" required>
                        </div>
                        <div class="form-group">
                            <label for="paese">Country:</label>
                            <input type="text" class="form-control" id="paese" name="paese" required>
                        </div>
                        <hr />
                        <div class="mt-2">
                            <h5>Order Summary</h5>
                            <p>Total: @String.Format("{0:F2}", Model.Sum(item => item.Prezzo * item.Quantita)) £</p>
                            <p>Estimated Delivery: @GetRandomDeliveryDays() business days</p>
                        </div>
                    </form>
                    @using (Html.BeginForm("Order", "Carrello", FormMethod.Post))
                    {
                        <input type="submit" class="btn btn-success " value="CONFIRM ORDER" />
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<script>
@functions {
    private int GetRandomDeliveryDays()
    {
        Random random = new Random();
        return random.Next(2, 8);
    }
}
</script>